SUR NOTRE DATASET :

QUERY 1

PREFIX schema: <https://schema.org/>
PREFIX ex: <https://example.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?name (STR(?weight) AS ?mass)
WHERE {
       ?meteorite schema:name ?name ;
                          schema:weight ?weight .
}
ORDER BY DESC(?weight)
LIMIT 10

---------------------------------------------------------------------------------
QUERY 2

PREFIX schema: <https://schema.org/>
PREFIX ex: <https://example.org/>

SELECT ?name (STR(?weight) AS ?mass)
WHERE {
       ?meteorite schema:year ?year ;
                           schema:name ?name ;
                           schema:weight ?weight .
       FILTER(STR(?year) = "2003.0")
}
ORDER BY DESC(?weight)
LIMIT 1

---------------------------------------------------------------------------------

AVEC AUTRES EQUIPES :

QUERY 1
(Accidents) Une météorite et accident qui se sont passés à moins de 100km)

PREFIX schema: <https://schema.org/>
PREFIX ns1: <https://www.geonames.org/ontology#>
PREFIX ns2: <https://www.geonames.org/ontology#>

SELECT DISTINCT ?meteoriteName ?streetAddress (STR(?approxDistanceInKm) AS ?DistanceKM)
WHERE {
  SERVICE <http://localhost:3030/meteorites2/query> {
    ?meteorite ns2:latitude ?latMeteo ;
               ns2:longitude ?longMeteo ;
               schema:name ?meteoriteName .
  }
  SERVICE <http://localhost:3030/accidents2/query> {
    ?accident ns1:latitude ?latAcc ;
              ns1:longitude ?longAcc ;
              schema:streetAddress ?streetAddress .
  }

  BIND(ABS(?latMeteo - ?latAcc) AS ?deltaLat)
  BIND(ABS(?longMeteo - ?longAcc) AS ?deltaLong)

  BIND(111.32 * (?deltaLat + ?deltaLong) AS ?approxDistanceInKm)
  FILTER(?approxDistanceInKm < 100)
}
ORDER BY ?approxDistanceInKm
